name: Connexion Alwaysdata

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  connexion:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Connexion SSH avec le serveur
      uses: appleboy/ssh-action@master
      with:
        host: ssh-${{ secrets.USERNAME }}.alwaysdata.net
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd $HOME/www/

          # Ajouter ici les commandes à exécuter sur le serveur
          git pull
          composer install
          php artisan migrate
          php artisan cache:clear
          php artisan config:cache
          php artisan optimize
          echo "Connexion réussie !"

